#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Compare Task 15 tax_base_update outputs against original upstream outputs.
Used to verify that the optimized scripts produce results consistent with the original pipeline.
"""

import os
import sys
import hashlib
import pandas as pd
from openpyxl import load_workbook

ROOT = '/home/xydeng/Metagenomics'
RES = os.path.join(ROOT, 'Result_update')
ORIG_MEGAHIT = os.path.join(ROOT, 'megahit_update_V2')
ORIG_PRODIGAL = os.path.join(ROOT, 'prodigal_original')
ORIG_BOWTIE = os.path.join(ROOT, 'bowtie_original')
ORIG_ANNO = os.path.join(ROOT, 'anno_original/Annotation')


def md5(path):
    h = hashlib.md5()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(8 * 1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def compare_md5(label, path_a, path_b):
    if not os.path.exists(path_a):
        return f'[SKIP] {label}: {path_a} 不存在'
    if not os.path.exists(path_b):
        return f'[SKIP] {label}: {path_b} 不存在'
    a, b = md5(path_a), md5(path_b)
    status = 'PASS' if a == b else 'DIFF'
    return f'[{status}] {label}\n  A: {path_a}\n  B: {path_b}\n  A md5: {a}\n  B md5: {b}'


def compare_excel(label, path_a, path_b, sort_first=True):
    if not os.path.exists(path_a):
        return f'[SKIP] {label}: {path_a} 不存在'
    if not os.path.exists(path_b):
        return f'[SKIP] {label}: {path_b} 不存在'
    try:
        a = pd.ExcelFile(path_a)
        b = pd.ExcelFile(path_b)
        if a.sheet_names != b.sheet_names:
            return f'[DIFF-sheets] {label}: sheet names differ\n  A: {a.sheet_names}\n  B: {b.sheet_names}'
        diffs = []
        for sheet in a.sheet_names:
            df_a = pd.read_excel(path_a, sheet_name=sheet, dtype=str)
            df_b = pd.read_excel(path_b, sheet_name=sheet, dtype=str)
            if sort_first:
                if not df_a.empty:
                    df_a = df_a.sort_values(by=list(df_a.columns), axis=0).reset_index(drop=True)
                if not df_b.empty:
                    df_b = df_b.sort_values(by=list(df_b.columns), axis=0).reset_index(drop=True)
            if df_a.shape != df_b.shape:
                diffs.append(f'{sheet}: shape A{df_a.shape} != B{df_b.shape}')
                continue
            if not df_a.equals(df_b):
                diffs.append(f'{sheet}: values differ')
        if diffs:
            return f'[DIFF-values] {label}\n  ' + '\n  '.join(diffs)
        return f'[PASS] {label}: {path_a} vs {path_b} ({len(a.sheet_names)} sheets)'
    except Exception as e:
        return f'[ERROR] {label}: {e}'


def compare_csv_summary(label, path_a, path_b, sort_cols=None):
    if not os.path.exists(path_a) or not os.path.exists(path_b):
        return f'[SKIP] {label}: 文件缺失'
    try:
        a = pd.read_csv(path_a, dtype=str)
        b = pd.read_csv(path_b, dtype=str)
        if a.shape != b.shape:
            return f'[DIFF] {label}: shape A{a.shape} != B{b.shape}'
        if sort_cols and all(c in a.columns for c in sort_cols):
            a = a.sort_values(by=sort_cols).reset_index(drop=True)
            b = b.sort_values(by=sort_cols).reset_index(drop=True)
        if not a.equals(b):
            return f'[DIFF] {label}: values differ'
        return f'[PASS] {label}: {path_a} vs {path_b} {a.shape}'
    except Exception as e:
        return f'[ERROR] {label}: {e}'


def main():
    lines = []
    lines.append('Task 15 tax_base_update 一致性检查报告')
    lines.append('=' * 60)

    # 1. MEGAHIT final.contigs.fa copies
    for sample in ['CK-1', 'CK-2', 'CK-3', 'T-1', 'T-2', 'T-3']:
        lines.append(compare_md5(
            f'final.contigs.fa ({sample})',
            os.path.join(ORIG_MEGAHIT, sample, 'final.contigs.fa'),
            os.path.join(RES, 'group1/2-Assembly', sample, 'final.contigs.fa')
        ))

    # 2. assembly_stat.xlsx (original generated by original megahit_statistics.py vs update output)
    lines.append(compare_excel(
        'assembly_stat.xlsx',
        os.path.join(ORIG_MEGAHIT, 'assembly_stat.xlsx'),
        os.path.join(RES, 'group1/2-Assembly/assembly_stat.xlsx')
    ))

    # 3. Prodigal outputs
    lines.append(compare_md5(
        'unique_gene.fasta',
        os.path.join(ORIG_PRODIGAL, 'unique_gene.fasta'),
        os.path.join(RES, 'group1/3-GenePredict/unique_gene.fasta')
    ))
    lines.append(compare_excel(
        'unique_gene.stat.xlsx',
        os.path.join(ORIG_PRODIGAL, 'unique_gene.stat.xlsx'),
        os.path.join(RES, 'group1/3-GenePredict/unique_gene.stat.xlsx')
    ))
    lines.append('[INFO] unique_gene.length.txt 为 gene_length.R 生成的长度分布表，与上游 '
                 'prodigal_original/unique_length.txt（逐基因长度）用途不同，不作为复制文件比较。')

    # 4. BWA outputs
    lines.append(compare_md5(
        'gene_count.csv',
        os.path.join(ORIG_BOWTIE, 'gene_count.csv'),
        os.path.join(RES, 'group1/4-GeneAbundance/gene_count.csv')
    ))
    lines.append(compare_md5(
        'gene_tpm.csv',
        os.path.join(ORIG_BOWTIE, 'gene_tpm.csv'),
        os.path.join(RES, 'group1/4-GeneAbundance/gene_tpm.csv')
    ))

    # 5. Sample correlation / Venn (no original Result persisted; report dimensions)
    corr_path = os.path.join(RES, 'group1/4-GeneAbundance/Sample_correlation/correlation.xlsx')
    if os.path.exists(corr_path):
        xls = pd.ExcelFile(corr_path)
        df_corr = pd.read_excel(corr_path, sheet_name=0, dtype=str)
        lines.append(f'[INFO] sample correlation.xlsx sheets: {xls.sheet_names}, shape: {df_corr.shape}')
    venn_path = os.path.join(RES, 'group1/4-GeneAbundance/Venn/upset.pdf')
    lines.append(f'[INFO] upset.pdf exists: {os.path.exists(venn_path)}')

    # 6. Taxonomy gene.taxonomy.csv
    lines.append(compare_md5(
        'gene.taxonomy.csv',
        os.path.join(ORIG_ANNO, 'gene.taxonomy.csv'),
        os.path.join(RES, 'group1/5-TaxAnnotation/1.Tables/gene.taxonomy.csv')
    ))

    # 7. All.taxonomy.csv from original vs update: original is per-gene, update is aggregated.
    lines.append('[INFO] All.taxonomy.csv：上游 anno_original/Annotation/All/All.taxonomy.csv 为逐基因表（约 104 万行），'
                 'Result_update 中 Samples/All/All.taxonomy.csv 为按分类层级聚合表（约 1.3 万行），二者属于不同处理阶段，'
                 '不直接比较 md5。')

    # 8. Taxonomy rank xlsx: verify group means equal sample means
    ranks = ['kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species']
    sample_cols = ['CK-1', 'CK-2', 'CK-3', 'T-1', 'T-2', 'T-3']
    group_cols = ['CK组', 'T组']
    all_match = True
    mismatch = []
    for rank in ranks:
        sample_xlsx = os.path.join(RES, f'group1/5-TaxAnnotation/1.Tables/Samples/All/{rank}.xlsx')
        group_xlsx = os.path.join(RES, f'group1/5-TaxAnnotation/1.Tables/Groups/All/{rank}.xlsx')
        if not os.path.exists(sample_xlsx) or not os.path.exists(group_xlsx):
            continue
        s = pd.read_excel(sample_xlsx, sheet_name='tpm', index_col=0)
        g = pd.read_excel(group_xlsx, sheet_name='tpm', index_col=0)
        ck_mean = s[['CK-1', 'CK-2', 'CK-3']].mean(axis=1)
        t_mean = s[['T-1', 'T-2', 'T-3']].mean(axis=1)
        ck_ok = (ck_mean.round(6) == g['CK组'].round(6)).all()
        t_ok = (t_mean.round(6) == g['T组'].round(6)).all()
        if not (ck_ok and t_ok):
            all_match = False
            mismatch.append(rank)
    if mismatch:
        lines.append(f'[FAIL] 以下分类等级组均值与样本均值不一致: {", ".join(mismatch)}')
    else:
        lines.append('[PASS] 所有 7 个分类等级的 Groups/All 均值均等于 Samples/All 对应样本均值（CK组/T组）。')

    # 9. Krona html (generated, no original; report existence)
    krona_path = os.path.join(RES, 'group1/5-TaxAnnotation/2.Krona/krona.html')
    lines.append(f'[INFO] krona.html exists: {os.path.exists(krona_path)}, size: {os.path.getsize(krona_path) if os.path.exists(krona_path) else 0} bytes')

    lines.append('=' * 60)

    report = '\n'.join(lines)
    print(report)
    out = '/home/xydeng/Metagenomics/scripts_dxy/logs/15_tax_base_update_consistency_report.txt'
    with open(out, 'w', encoding='utf-8') as f:
        f.write(report + '\n')
    print(f'\n报告已保存: {out}')


if __name__ == '__main__':
    main()
